<a href="https://colab.research.google.com/github/thspanos/AI-LAb/blob/main/Thomas%20Spanos%20c1%20u4%20q5%20phishing%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/thspanos/AI-LAb/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0  interpark.com        0        0           1          2            0   
1      ripe6.net        0        0           0          2            0   
2   soyalejo.com        0        0           0          2            0   
3         qz.com        0        0           1          2            0   
4         ap.org        0        0           1          4            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            1           1   
1             0        0              0           0            1           0   
2             0        0              0           0            1           0   
3             0        0              0           0            1           0   
4             0        0              0           0            1           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           0       0           0            1             0      1  
2           0       0           0            1             0      1  
3           1       0           0            1             0      0  
4           1       0           0            1             1      0

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          2            0             0   
1        0        0           0          2            0             0   
2        0        0           0          2            0             0   
3        0        0           1          2            0             0   
4        0        0           1          4            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           1           1   
1        0              0           0            1           0           0   
2        0              0           0            1           0           0   
3        0              0           0            1           0           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             1

In [6]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [9]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [11]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.804
Precision: 0.8243544752027047
Recall: 0.804
F1 Score: 0.800854835366275
Confusion Matrix:
[[1395  106]
 [ 482 1017]]

SVC Metrics:
Accuracy: 0.8366666666666667
Precision: 0.8680265065328201
Recall: 0.8366666666666667
F1 Score: 0.8330922662306203
Confusion Matrix:
[[1475   26]
 [ 464 1035]]

RandomForestClassifier Metrics:
Accuracy: 0.864
Precision: 0.8705771210070243
Recall: 0.864
F1 Score: 0.8633867306843158
Confusion Matrix:
[[1397  104]
 [ 304 1195]]


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.854
Precision: 0.8677296444542352
Recall: 0.854
F1 Score: 0.8526131636427596
Confusion Matrix:
[[1427   74]
 [ 364 1135]]

KNeighborsClassifier Metrics:
Accuracy: 0.8526666666666667
Precision: 0.8574660809161738
Recall: 0.8526666666666667
F1 Score: 0.8521636090318562
Confusion Matrix:
[[1367  134]
 [ 308 1191]]

DecisionTreeClassifier Metrics:
Accuracy: 0.864
Precision: 0.8718423170525136
Recall: 0.864
F1 Score: 0.8632713526073552
Confusion Matrix:
[[1406   95]
 [ 313 1186]]


In [12]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
5  DecisionTreeClassifier  0.864000   0.871842  0.864000  0.863271
2  RandomForestClassifier  0.864000   0.870577  0.864000  0.863387
3           MLPClassifier  0.854000   0.867730  0.854000  0.852613
4    KNeighborsClassifier  0.852667   0.857466  0.852667  0.852164
1                     SVC  0.836667   0.868027  0.836667  0.833092
0      LogisticRegression  0.804000   0.824354  0.804000  0.800855
