<a href="https://colab.research.google.com/github/thspanos/AI-LAb/blob/main/Thomas%20Spanos%20c1%20u4%20q5%20phishing%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/thspanos/AI-LAb/main/Data/phishing_dataset.csv', delimiter=',')

In [15]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0       twitter.com        0        0           1          1            0   
1      estogeek.com        0        0           1          5            0   
2     firstcbuk.com        0        0           0          1            0   
3  evisionlegal.com        0        0           1          5            0   
4      tradoauc.com        0        0           0          2            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            1           1   
1             0        0              0           0            1           0   
2             0        0              0           0            1           0   
3             0        0              0           0            1           0   
4             0        0              0           0            0           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           0       0           0            1             0      1  
2           1       0           0            1             0      1  
3           0       0           0            1             0      1  
4           1       0           0            1             0      1

In [16]:
X = data.drop(['Domain', 'Label'], axis=1)

In [17]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          1            0             0   
1        0        0           1          5            0             0   
2        0        0           0          1            0             0   
3        0        0           1          5            0             0   
4        0        0           0          2            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           1           1   
1        0              0           0            1           0           0   
2        0              0           0            1           0           1   
3        0              0           0            1           0           0   
4        0              0           0            0           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [18]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [20]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [22]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.798
Precision: 0.823715083721743
Recall: 0.798
F1 Score: 0.7946091059392892
Confusion Matrix:
[[1376   95]
 [ 511 1018]]

SVC Metrics:
Accuracy: 0.828
Precision: 0.8601860066657843
Recall: 0.828
F1 Score: 0.8246695249488081
Confusion Matrix:
[[1435   36]
 [ 480 1049]]

RandomForestClassifier Metrics:
Accuracy: 0.8546666666666667
Precision: 0.864550700774869
Recall: 0.8546666666666667
F1 Score: 0.8539449068257957
Confusion Matrix:
[[1374   97]
 [ 339 1190]]


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8536666666666667
Precision: 0.8634460270699096
Recall: 0.8536666666666667
F1 Score: 0.8529469063273328
Confusion Matrix:
[[1372   99]
 [ 340 1189]]

KNeighborsClassifier Metrics:
Accuracy: 0.8496666666666667
Precision: 0.8640205897893138
Recall: 0.8496666666666667
F1 Score: 0.8485094322290573
Confusion Matrix:
[[1392   79]
 [ 372 1157]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8536666666666667
Precision: 0.8656782151795391
Recall: 0.8536666666666667
F1 Score: 0.8527549261402294
Confusion Matrix:
[[1385   86]
 [ 353 1176]]


In [23]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.854667   0.864551  0.854667  0.853945
3           MLPClassifier  0.853667   0.863446  0.853667  0.852947
5  DecisionTreeClassifier  0.853667   0.865678  0.853667  0.852755
4    KNeighborsClassifier  0.849667   0.864021  0.849667  0.848509
1                     SVC  0.828000   0.860186  0.828000  0.824670
0      LogisticRegression  0.798000   0.823715  0.798000  0.794609
